# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deviceapps.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64\x65viceapps.proto\"|\n\nDeviceApps\x12\"\n\x06\x64\x65vice\x18\x01 \x01(\x0b\x32\x12.DeviceApps.Device\x12\x0c\n\x04\x61pps\x18\x02 \x03(\r\x12\x0b\n\x03lat\x18\x03 \x01(\x01\x12\x0b\n\x03lon\x18\x04 \x01(\x01\x1a\"\n\x06\x44\x65vice\x12\n\n\x02id\x18\x01 \x01(\x0c\x12\x0c\n\x04type\x18\x02 \x01(\x0c')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'deviceapps_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_DEVICEAPPS']._serialized_start=20
  _globals['_DEVICEAPPS']._serialized_end=144
  _globals['_DEVICEAPPS_DEVICE']._serialized_start=110
  _globals['_DEVICEAPPS_DEVICE']._serialized_end=144
# @@protoc_insertion_point(module_scope)
